version: "3.8"

services:
  mini-do: # 서비스 이름
    container_name: mini-do
    build:
      # context: ./mini-do
      context: .
      dockerfile: Dockerfile
      #dockerfile: prod.Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    # restart: unless-stopped
    # depends_on:
    #   - db
    restart: always
    # environment:
    #   - NODE_ENV=production
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data


# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true





# | Can't reach database server at `localhost`:`5432`
# mini-do       |
# mini-do       | Please make sure your database server is running at `localhost`:`5432`. {



# volumes:
#   db:



# docker compose up -d -f docker-compose.prod.yml --build