version: "3.8"


# docker run --name nginx -d -p 80:80 --restart always nginx:1.22.1-alpine
# docker run --name mini-do -d -p 3000:3000 mini-do:latest


services:
  mini-do:
    # container_name: mini-do
    # image: mini-do:latest
    # user: root
    restart: always
    # build: .
    ports:
      - 3000:3000


# services:
#   mini-do: # 서비스 이름
#     container_name: mini-do
#     build:
#       # context: ./mini-do
#       context: .
#       dockerfile: Dockerfile
#       #dockerfile: prod.Dockerfile
#     volumes:
#       - .:/app
#       - /app/node_modules
#     # restart: unless-stopped
#     # depends_on:
#     #   - db
#     restart: always
#     # environment:
#     #   - NODE_ENV=production
#     ports:
#       - 3000:3000
 




#

#






# | Can't reach database server at `localhost`:`5432`
# mini-do       |
# mini-do       | Please make sure your database server is running at `localhost`:`5432`. {



# volumes:
#   db:



# docker compose up -d -f docker-compose.prod.yml --build
# docker run --name mini-do -d -p 3000:3000 mini-do:latest


